name: Dockerize Contrib Scripts

on:
  push:
    branches:
      - feature/dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Build contributors-github container
        run: docker build --tag ghcr.io/kaakaww/contributors-github --target contributors-github .
      - name: Build contributors-local container
        run: docker build --tag ghcr.io/kaakaww/contributors-local --target contributors-local .
